import oracledb from 'oracledb';

export interface OracleAutonomousConfig {
  user: string;
  password: string;
  connectString: string;
  walletLocation?: string;
  walletPassword?: string;
}

export function getOracleAutonomousConfigFromEnv(env: NodeJS.ProcessEnv = process.env): OracleAutonomousConfig | null {
  const user = env.ORACLE_DB_USER || env.ORACLE_USER;
  const password = env.ORACLE_DB_PASSWORD || env.ORACLE_PASSWORD;
  const connectString = env.ORACLE_DB_CONNECT_STRING || env.ORACLE_CONNECT_STRING;

  if (!user || !password || !connectString) return null;

  return {
    user,
    password,
    connectString,
    walletLocation: env.ORACLE_DB_WALLET_LOCATION || env.TNS_ADMIN,
    walletPassword: env.ORACLE_DB_WALLET_PASSWORD,
  };
}

export async function openOracleAutonomousConnection(config: OracleAutonomousConfig): Promise<oracledb.Connection> {
  const connectionConfig: oracledb.ConnectionAttributes = {
    user: config.user,
    password: config.password,
    connectString: config.connectString,
  };

  if (config.walletLocation) {
    connectionConfig.configDir = config.walletLocation;
    connectionConfig.walletLocation = config.walletLocation;
  }

  if (config.walletPassword) {
    connectionConfig.walletPassword = config.walletPassword;
  }

  return oracledb.getConnection(connectionConfig);
}

export async function ensureOracleSmokeTable(connection: oracledb.Connection): Promise<void> {
  const table = await connection.execute<{ COUNT: number }>(
    `SELECT COUNT(*) AS count FROM user_tables WHERE table_name = 'TRIPPI_ORACLE_SMOKE'`,
    [],
    { outFormat: oracledb.OUT_FORMAT_OBJECT },
  );
  const exists = Number(table.rows?.[0]?.COUNT ?? 0) > 0;
  if (exists) return;

  await connection.execute(`
    CREATE TABLE trippi_oracle_smoke (
      id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      payload CLOB CHECK (payload IS JSON)
    )
  `);
  await connection.commit();
}

export async function ensureOracleMirrorTables(connection: oracledb.Connection): Promise<void> {
  const existing = await connection.execute<{ TABLE_NAME: string }>(
    `
      SELECT table_name
      FROM user_tables
      WHERE table_name IN ('TRIPPI_SQLITE_MIRROR', 'TRIPPI_SQLITE_MIRROR_RUNS')
    `,
    [],
    { outFormat: oracledb.OUT_FORMAT_OBJECT },
  );
  const names = new Set((existing.rows ?? []).map((row) => row.TABLE_NAME));

  if (!names.has('TRIPPI_SQLITE_MIRROR')) {
    await connection.execute(`
      CREATE TABLE trippi_sqlite_mirror (
        table_name VARCHAR2(128) NOT NULL,
        row_key VARCHAR2(512) NOT NULL,
        payload CLOB CHECK (payload IS JSON),
        mirrored_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT trippi_sqlite_mirror_pk PRIMARY KEY (table_name, row_key)
      )
    `);
  }

  if (!names.has('TRIPPI_SQLITE_MIRROR_RUNS')) {
    await connection.execute(`
      CREATE TABLE trippi_sqlite_mirror_runs (
        run_id VARCHAR2(64) PRIMARY KEY,
        source_db_path VARCHAR2(1024) NOT NULL,
        started_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        finished_at TIMESTAMP,
        table_count NUMBER DEFAULT 0 NOT NULL,
        row_count NUMBER DEFAULT 0 NOT NULL,
        status VARCHAR2(32) DEFAULT 'running' NOT NULL,
        error_message CLOB
      )
    `);
  }

  await connection.commit();
}
