import { asyncDb } from '../db/asyncDatabase';
import { resolveDbProvider } from '../db/providerMode';
import { getBillingSubscriptionForUser } from './subscriptionService';

import crypto from 'crypto';

export const REFERRAL_BONUS_DAYS = 7;
export const REFERRAL_MAX_BONUS_DAYS = 90;
const DAY_MS = 24 * 60 * 60 * 1000;

interface ReferralCodeRow {
  id: number;
  user_id: number;
  code: string;
  created_at: string;
  revoked_at: string | null;
}

interface ReferralBonusAccountRow {
  user_id: number;
  pending_days: number;
  active_until: string | null;
  last_prompted_active_until: string | null;
  created_at: string;
  updated_at: string;
}

interface ReferralValidationInternal {
  code: string;
  referrer_user_id: number;
  referrer_username: string;
}

export interface ReferralBonusState {
  active: boolean;
  activeUntil: string | null;
  pendingDays: number;
  daysRemaining: number;
  expiresSoon: boolean;
  maxDays: number;
}

export interface ReferralSummary {
  code: string | null;
  referral_url: string | null;
  reward_days: number;
  max_bonus_days: number;
  successful_referrals: number;
  pending_bonus_days: number;
  active_bonus_until: string | null;
  active_bonus_days_remaining: number;
  expires_soon: boolean;
}

export interface ReferralExpiryWarningTrip {
  id: number;
  title: string;
  start_date: string | null;
  end_date: string | null;
  created_at: string | null;
}

export interface ReferralExpiryWarning {
  show: boolean;
  active_until: string | null;
  trips: ReferralExpiryWarningTrip[];
}

let referralStorageReady: Promise<void> | null = null;

function isAlreadyExistsError(err: unknown): boolean {
  const message = err instanceof Error ? err.message : String(err);
  return /ORA-00955|ORA-01408|ORA-02261/.test(message);
}

async function execOracleReferralDdl(sql: string): Promise<void> {
  try {
    await asyncDb.exec(sql);
  } catch (err) {
    if (isAlreadyExistsError(err)) return;
    throw err;
  }
}

async function ensureOracleReferralStorage(): Promise<void> {
  await execOracleReferralDdl(`
    CREATE TABLE referral_codes (
      id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
      user_id NUMBER(19,0) NOT NULL,
      code VARCHAR2(64 CHAR) NOT NULL,
      created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
      revoked_at VARCHAR2(4000 CHAR),
      CONSTRAINT pk_referral_codes PRIMARY KEY (id),
      CONSTRAINT uq_referral_codes_user UNIQUE (user_id),
      CONSTRAINT uq_referral_codes_code UNIQUE (code),
      CONSTRAINT fk_referral_codes_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
    )
  `);
  await execOracleReferralDdl('CREATE INDEX idx_referral_codes_user ON referral_codes(user_id)');
  await execOracleReferralDdl('CREATE INDEX idx_referral_codes_code ON referral_codes(code)');

  await execOracleReferralDdl(`
    CREATE TABLE referrals (
      id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
      referrer_user_id NUMBER(19,0) NOT NULL,
      referred_user_id NUMBER(19,0) NOT NULL,
      referral_code VARCHAR2(64 CHAR) NOT NULL,
      created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT pk_referrals PRIMARY KEY (id),
      CONSTRAINT uq_referrals_referred UNIQUE (referred_user_id),
      CONSTRAINT ck_referrals_no_self CHECK (referrer_user_id != referred_user_id),
      CONSTRAINT fk_referrals_referrer FOREIGN KEY (referrer_user_id) REFERENCES users(id) ON DELETE CASCADE,
      CONSTRAINT fk_referrals_referred FOREIGN KEY (referred_user_id) REFERENCES users(id) ON DELETE CASCADE
    )
  `);
  await execOracleReferralDdl('CREATE INDEX idx_referrals_referrer ON referrals(referrer_user_id, created_at DESC)');
  await execOracleReferralDdl('CREATE INDEX idx_referrals_referred ON referrals(referred_user_id)');

  await execOracleReferralDdl(`
    CREATE TABLE referral_bonus_accounts (
      user_id NUMBER(19,0) NOT NULL,
      pending_days NUMBER(10,0) DEFAULT 0 NOT NULL,
      active_until VARCHAR2(4000 CHAR),
      last_prompted_active_until VARCHAR2(4000 CHAR),
      created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT pk_referral_bonus_accounts PRIMARY KEY (user_id),
      CONSTRAINT fk_referral_bonus_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
    )
  `);
  await execOracleReferralDdl('CREATE INDEX idx_referral_bonus_active_until ON referral_bonus_accounts(active_until)');
}

async function ensureSqliteReferralStorage(): Promise<void> {
  await asyncDb.exec(`
    CREATE TABLE IF NOT EXISTS referral_codes (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      code TEXT NOT NULL UNIQUE,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      revoked_at TEXT,
      UNIQUE(user_id)
    );
    CREATE INDEX IF NOT EXISTS idx_referral_codes_user ON referral_codes(user_id);
    CREATE INDEX IF NOT EXISTS idx_referral_codes_code ON referral_codes(code);

    CREATE TABLE IF NOT EXISTS referrals (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      referrer_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      referred_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      referral_code TEXT NOT NULL,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(referred_user_id),
      CHECK(referrer_user_id != referred_user_id)
    );
    CREATE INDEX IF NOT EXISTS idx_referrals_referrer ON referrals(referrer_user_id, created_at DESC);
    CREATE INDEX IF NOT EXISTS idx_referrals_referred ON referrals(referred_user_id);

    CREATE TABLE IF NOT EXISTS referral_bonus_accounts (
      user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
      pending_days INTEGER NOT NULL DEFAULT 0,
      active_until TEXT,
      last_prompted_active_until TEXT,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    );
    CREATE INDEX IF NOT EXISTS idx_referral_bonus_active_until ON referral_bonus_accounts(active_until);
  `);
}

async function ensureReferralStorage(): Promise<void> {
  if (!referralStorageReady) {
    referralStorageReady =
      resolveDbProvider() === 'oracle-async'
        ? ensureOracleReferralStorage()
        : ensureSqliteReferralStorage().catch((err) => {
            referralStorageReady = null;
            throw err;
          });
  }
  await referralStorageReady;
}

function cleanReferralCode(value: unknown): string {
  return typeof value === 'string' ? value.trim().replace(/[^a-zA-Z0-9_-]/g, '').slice(0, 64) : '';
}

function buildReferralUrl(code: string | null): string | null {
  if (!code) return null;
  const base =
    process.env.APP_URL?.trim().replace(/\/+$/, '') ||
    process.env.FRONTEND_URL?.trim().replace(/\/+$/, '') ||
    `http://localhost:${Number(process.env.PORT) || 3001}`;
  return `${base}/register?ref=${encodeURIComponent(code)}`;
}

function parseActiveUntil(value: string | null | undefined): Date | null {
  if (!value) return null;
  const parsed = new Date(value);
  return Number.isNaN(parsed.getTime()) ? null : parsed;
}

function daysRemainingUntil(activeUntil: Date | null, now = new Date()): number {
  if (!activeUntil || activeUntil <= now) return 0;
  return Math.ceil((activeUntil.getTime() - now.getTime()) / DAY_MS);
}

async function hasActivePaidAccess(userId: number): Promise<boolean> {
  const billing = await getBillingSubscriptionForUser(userId);
  const status = billing.status.toLowerCase();
  return status === 'active' || status === 'trialing';
}

async function ensureBonusAccount(userId: number): Promise<ReferralBonusAccountRow> {
  await ensureReferralStorage();
  await asyncDb
    .prepare(
      `
      INSERT OR IGNORE INTO referral_bonus_accounts (user_id, pending_days, updated_at)
      VALUES (?, 0, CURRENT_TIMESTAMP)
    `,
    )
    .run(userId);
  const account = await asyncDb
    .prepare('SELECT * FROM referral_bonus_accounts WHERE user_id = ?')
    .get<ReferralBonusAccountRow>(userId);
  if (!account) throw new Error('Failed to initialize referral bonus account.');
  return account;
}

async function getBonusAccount(userId: number): Promise<ReferralBonusAccountRow | undefined> {
  await ensureReferralStorage();
  return asyncDb
    .prepare('SELECT * FROM referral_bonus_accounts WHERE user_id = ?')
    .get<ReferralBonusAccountRow>(userId);
}

async function updateBonusAccount(
  userId: number,
  update: Pick<ReferralBonusAccountRow, 'pending_days' | 'active_until'>,
): Promise<void> {
  await asyncDb
    .prepare(
      `
      UPDATE referral_bonus_accounts
      SET pending_days = ?, active_until = ?, updated_at = CURRENT_TIMESTAMP
      WHERE user_id = ?
    `,
    )
    .run(update.pending_days, update.active_until, userId);
}

export async function awardReferralBonusDays(
  userId: number,
  days = REFERRAL_BONUS_DAYS,
  options: { paidAccessActive?: boolean } = {},
): Promise<ReferralBonusState> {
  const account = await ensureBonusAccount(userId);
  const paidAccessActive = options.paidAccessActive ?? (await hasActivePaidAccess(userId));

  if (paidAccessActive) {
    const pendingDays = Math.min(REFERRAL_MAX_BONUS_DAYS, Number(account.pending_days || 0) + days);
    await updateBonusAccount(userId, { pending_days: pendingDays, active_until: account.active_until });
    return getReferralBonusState(userId, { paidAccessActive: true });
  }

  const now = new Date();
  const currentActiveUntil = parseActiveUntil(account.active_until);
  const base = currentActiveUntil && currentActiveUntil > now ? currentActiveUntil : now;
  const cappedUntil = new Date(Math.min(base.getTime() + days * DAY_MS, now.getTime() + REFERRAL_MAX_BONUS_DAYS * DAY_MS));
  await updateBonusAccount(userId, {
    pending_days: Number(account.pending_days || 0),
    active_until: cappedUntil.toISOString(),
  });
  return getReferralBonusState(userId, { paidAccessActive: false });
}

async function activatePendingReferralBonusIfNeeded(
  userId: number,
  account: ReferralBonusAccountRow,
  paidAccessActive: boolean,
): Promise<ReferralBonusAccountRow> {
  if (paidAccessActive || Number(account.pending_days || 0) <= 0) return account;
  const now = new Date();
  const activeUntil = parseActiveUntil(account.active_until);
  if (activeUntil && activeUntil > now) return account;

  const days = Math.min(REFERRAL_MAX_BONUS_DAYS, Number(account.pending_days || 0));
  const nextActiveUntil = new Date(now.getTime() + days * DAY_MS).toISOString();
  await updateBonusAccount(userId, { pending_days: 0, active_until: nextActiveUntil });
  return {
    ...account,
    pending_days: 0,
    active_until: nextActiveUntil,
  };
}

export async function getReferralBonusState(
  userId: number,
  options: { paidAccessActive?: boolean } = {},
): Promise<ReferralBonusState> {
  let account = await getBonusAccount(userId);
  if (!account) {
    return {
      active: false,
      activeUntil: null,
      pendingDays: 0,
      daysRemaining: 0,
      expiresSoon: false,
      maxDays: REFERRAL_MAX_BONUS_DAYS,
    };
  }

  const paidAccessActive = options.paidAccessActive ?? (await hasActivePaidAccess(userId));
  account = await activatePendingReferralBonusIfNeeded(userId, account, paidAccessActive);

  const now = new Date();
  const activeUntil = paidAccessActive ? null : parseActiveUntil(account.active_until);
  const daysRemaining = daysRemainingUntil(activeUntil, now);
  return {
    active: daysRemaining > 0,
    activeUntil: activeUntil && daysRemaining > 0 ? activeUntil.toISOString() : account.active_until,
    pendingDays: Number(account.pending_days || 0),
    daysRemaining,
    expiresSoon: daysRemaining > 0 && activeUntil!.getTime() - now.getTime() <= DAY_MS,
    maxDays: REFERRAL_MAX_BONUS_DAYS,
  };
}

async function referralCodeForUser(userId: number): Promise<ReferralCodeRow | undefined> {
  await ensureReferralStorage();
  return asyncDb
    .prepare('SELECT * FROM referral_codes WHERE user_id = ? AND revoked_at IS NULL')
    .get<ReferralCodeRow>(userId);
}

function generateReferralCode(): string {
  return crypto.randomBytes(9).toString('base64url').replace(/[^a-zA-Z0-9]/g, '').slice(0, 10);
}

export async function getOrCreateReferralCode(userId: number): Promise<ReferralCodeRow> {
  const existing = await referralCodeForUser(userId);
  if (existing) return existing;

  for (let attempt = 0; attempt < 8; attempt += 1) {
    const code = generateReferralCode();
    const inserted = await asyncDb
      .prepare('INSERT OR IGNORE INTO referral_codes (user_id, code) VALUES (?, ?)')
      .run(userId, code);
    const current = await referralCodeForUser(userId);
    if (current) return current;
    if (inserted.changes > 0) {
      throw new Error('Failed to read generated referral code.');
    }
  }
  throw new Error('Failed to generate a unique referral code.');
}

export async function validateReferralCodeInternal(codeInput: unknown): Promise<ReferralValidationInternal | null> {
  const code = cleanReferralCode(codeInput);
  if (!code) return null;
  await ensureReferralStorage();
  const row = await asyncDb
    .prepare(
      `
      SELECT rc.code, rc.user_id AS referrer_user_id, u.username AS referrer_username
      FROM referral_codes rc
      JOIN users u ON u.id = rc.user_id
      WHERE rc.code = ? AND rc.revoked_at IS NULL
    `,
    )
    .get<ReferralValidationInternal>(code);
  return row ?? null;
}

export async function validateReferralCodeForPublic(codeInput: unknown): Promise<{
  valid: boolean;
  code?: string;
  referrer_username?: string;
  reward_days: number;
}> {
  const referral = await validateReferralCodeInternal(codeInput);
  if (!referral) return { valid: false, reward_days: REFERRAL_BONUS_DAYS };
  return {
    valid: true,
    code: referral.code,
    referrer_username: referral.referrer_username,
    reward_days: REFERRAL_BONUS_DAYS,
  };
}

export async function completeReferralSignup(
  codeInput: unknown,
  referredUserId: number,
): Promise<{ applied: boolean; reason?: 'invalid' | 'self' | 'duplicate' }> {
  const referral = await validateReferralCodeInternal(codeInput);
  if (!referral) return { applied: false, reason: 'invalid' };
  if (referral.referrer_user_id === referredUserId) return { applied: false, reason: 'self' };

  const inserted = await asyncDb
    .prepare(
      `
      INSERT OR IGNORE INTO referrals (referrer_user_id, referred_user_id, referral_code)
      VALUES (?, ?, ?)
    `,
    )
    .run(referral.referrer_user_id, referredUserId, referral.code);

  if (inserted.changes === 0) return { applied: false, reason: 'duplicate' };

  await awardReferralBonusDays(referral.referrer_user_id);
  await awardReferralBonusDays(referredUserId, REFERRAL_BONUS_DAYS, { paidAccessActive: false });
  return { applied: true };
}

export async function getReferralSummary(userId: number, options: { create?: boolean } = {}): Promise<ReferralSummary> {
  await ensureReferralStorage();
  const code = options.create ? await getOrCreateReferralCode(userId) : await referralCodeForUser(userId);
  const stats = await asyncDb
    .prepare('SELECT COUNT(*) AS count FROM referrals WHERE referrer_user_id = ?')
    .get<{ count: number }>(userId);
  const bonus = await getReferralBonusState(userId);
  return {
    code: code?.code ?? null,
    referral_url: buildReferralUrl(code?.code ?? null),
    reward_days: REFERRAL_BONUS_DAYS,
    max_bonus_days: REFERRAL_MAX_BONUS_DAYS,
    successful_referrals: stats?.count ?? 0,
    pending_bonus_days: bonus.pendingDays,
    active_bonus_until: bonus.activeUntil,
    active_bonus_days_remaining: bonus.daysRemaining,
    expires_soon: bonus.expiresSoon,
  };
}

export async function listTripsThatWouldLock(userId: number): Promise<ReferralExpiryWarningTrip[]> {
  await ensureReferralStorage();
  return asyncDb
    .prepare(
      `
      SELECT id, title, start_date, end_date, created_at
      FROM trips
      WHERE user_id = ?
      ORDER BY created_at DESC, id DESC
      LIMIT -1 OFFSET 5
    `,
    )
    .all<ReferralExpiryWarningTrip>(userId);
}

export async function getReferralExpiryWarning(userId: number): Promise<ReferralExpiryWarning> {
  const account = await getBonusAccount(userId);
  if (!account?.active_until) return { show: false, active_until: null, trips: [] };

  const bonus = await getReferralBonusState(userId, { paidAccessActive: false });
  if (!bonus.active || !bonus.expiresSoon || !bonus.activeUntil) {
    return { show: false, active_until: bonus.activeUntil, trips: [] };
  }
  if (account.last_prompted_active_until === bonus.activeUntil) {
    return { show: false, active_until: bonus.activeUntil, trips: [] };
  }

  const trips = await listTripsThatWouldLock(userId);
  if (trips.length === 0) return { show: false, active_until: bonus.activeUntil, trips: [] };
  return { show: true, active_until: bonus.activeUntil, trips };
}

export async function dismissReferralExpiryWarning(userId: number, activeUntil: unknown): Promise<void> {
  const cleanActiveUntil = typeof activeUntil === 'string' && activeUntil.trim() ? activeUntil.trim() : null;
  if (!cleanActiveUntil) return;
  await ensureBonusAccount(userId);
  await asyncDb
    .prepare(
      `
      UPDATE referral_bonus_accounts
      SET last_prompted_active_until = ?, updated_at = CURRENT_TIMESTAMP
      WHERE user_id = ?
    `,
    )
    .run(cleanActiveUntil, userId);
}
