import { asyncDb } from '../db/asyncDatabase';
import { resolveDbProvider } from '../db/providerMode';

export const STRIPE_SUBSCRIPTION_STATUSES = [
  'incomplete',
  'incomplete_expired',
  'trialing',
  'active',
  'past_due',
  'canceled',
  'unpaid',
  'paused',
] as const;

export type StripeSubscriptionStatus = (typeof STRIPE_SUBSCRIPTION_STATUSES)[number];
export type BillingPlanKey = 'free' | 'trial' | 'pro' | 'agency' | string;

export interface BillingCustomer {
  id: number;
  user_id: number;
  stripe_customer_id: string;
  created_at: string;
  updated_at: string;
}

export interface BillingSubscription {
  id: number;
  user_id: number;
  billing_customer_id: number;
  stripe_customer_id: string;
  stripe_subscription_id: string;
  status: StripeSubscriptionStatus | string;
  plan_key: BillingPlanKey;
  stripe_price_id: string | null;
  current_period_start: string | null;
  current_period_end: string | null;
  trial_start: string | null;
  trial_end: string | null;
  cancel_at_period_end: 0 | 1;
  canceled_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface BillingSubscriptionState extends BillingSubscription {
  customer: BillingCustomer;
}

export interface BillingWebhookEvent {
  id: string;
  type: string;
  stripe_created: number | null;
  processed_at: string;
}

export interface UpsertStripeSubscriptionInput {
  userId: number;
  stripeCustomerId: string;
  stripeSubscriptionId: string;
  status: StripeSubscriptionStatus | string;
  planKey: BillingPlanKey;
  stripePriceId?: string | null;
  currentPeriodStart?: string | Date | null;
  currentPeriodEnd?: string | Date | null;
  trialStart?: string | Date | null;
  trialEnd?: string | Date | null;
  cancelAtPeriodEnd?: boolean;
  canceledAt?: string | Date | null;
}

export interface FreeBillingState {
  user_id: number;
  status: 'free';
  plan_key: 'free';
  stripe_customer_id: null;
  stripe_subscription_id: null;
  stripe_price_id: null;
  current_period_start: null;
  current_period_end: null;
  trial_start: null;
  trial_end: null;
  cancel_at_period_end: 0;
  canceled_at: null;
}

let billingStorageReady: Promise<void> | null = null;

function isoOrNull(value: string | Date | null | undefined): string | null {
  if (!value) return null;
  return value instanceof Date ? value.toISOString() : value;
}

function isAlreadyExistsError(err: unknown): boolean {
  const message = err instanceof Error ? err.message : String(err);
  return /ORA-00955|ORA-01408|ORA-02261/.test(message);
}

async function execOracleBillingDdl(sql: string): Promise<void> {
  try {
    await asyncDb.exec(sql);
  } catch (err) {
    if (isAlreadyExistsError(err)) return;
    throw err;
  }
}

async function ensureOracleBillingStorage(): Promise<void> {
  await execOracleBillingDdl(`
    CREATE TABLE billing_customers (
      id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
      user_id NUMBER(19,0) NOT NULL,
      stripe_customer_id VARCHAR2(255 CHAR) NOT NULL,
      created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT pk_billing_customers PRIMARY KEY (id),
      CONSTRAINT uq_billing_customers_user UNIQUE (user_id),
      CONSTRAINT uq_billing_customers_stripe UNIQUE (stripe_customer_id),
      CONSTRAINT fk_billing_customers_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
    )
  `);

  await execOracleBillingDdl(`
    CREATE TABLE billing_subscriptions (
      id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
      user_id NUMBER(19,0) NOT NULL,
      billing_customer_id NUMBER(19,0) NOT NULL,
      stripe_customer_id VARCHAR2(255 CHAR) NOT NULL,
      stripe_subscription_id VARCHAR2(255 CHAR) NOT NULL,
      status VARCHAR2(64 CHAR) NOT NULL,
      plan_key VARCHAR2(64 CHAR) DEFAULT 'free' NOT NULL,
      stripe_price_id VARCHAR2(255 CHAR),
      current_period_start VARCHAR2(4000 CHAR),
      current_period_end VARCHAR2(4000 CHAR),
      trial_start VARCHAR2(4000 CHAR),
      trial_end VARCHAR2(4000 CHAR),
      cancel_at_period_end NUMBER(19,0) DEFAULT 0 NOT NULL,
      canceled_at VARCHAR2(4000 CHAR),
      created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT pk_billing_subscriptions PRIMARY KEY (id),
      CONSTRAINT uq_billing_subscriptions_stripe UNIQUE (stripe_subscription_id),
      CONSTRAINT fk_billing_subscriptions_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
      CONSTRAINT fk_billing_subscriptions_customer FOREIGN KEY (billing_customer_id)
        REFERENCES billing_customers(id) ON DELETE CASCADE
    )
  `);

  await execOracleBillingDdl(`
    CREATE INDEX idx_billing_subscriptions_user ON billing_subscriptions(user_id)
  `);
  await execOracleBillingDdl(`
    CREATE INDEX idx_billing_subscriptions_customer ON billing_subscriptions(stripe_customer_id)
  `);
  await execOracleBillingDdl(`
    CREATE INDEX idx_billing_subscriptions_status ON billing_subscriptions(status)
  `);

  await execOracleBillingDdl(`
    CREATE TABLE billing_webhook_events (
      id VARCHAR2(255 CHAR) NOT NULL,
      type VARCHAR2(255 CHAR) NOT NULL,
      stripe_created NUMBER(19,0),
      processed_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT pk_billing_webhook_events PRIMARY KEY (id)
    )
  `);

  await execOracleBillingDdl(`
    CREATE INDEX idx_billing_webhook_events_processed_at ON billing_webhook_events(processed_at)
  `);
}

async function ensureBillingStorage(): Promise<void> {
  if (resolveDbProvider() !== 'oracle-async') return;
  if (!billingStorageReady) {
    billingStorageReady = ensureOracleBillingStorage().catch((err) => {
      billingStorageReady = null;
      throw err;
    });
  }
  await billingStorageReady;
}

export async function getBillingCustomerForUser(userId: number): Promise<BillingCustomer | undefined> {
  await ensureBillingStorage();
  return asyncDb.prepare('SELECT * FROM billing_customers WHERE user_id = ?').get<BillingCustomer>(userId);
}

export async function getBillingCustomerByStripeId(stripeCustomerId: string): Promise<BillingCustomer | undefined> {
  await ensureBillingStorage();
  return asyncDb
    .prepare('SELECT * FROM billing_customers WHERE stripe_customer_id = ?')
    .get<BillingCustomer>(stripeCustomerId);
}

export async function userExists(userId: number): Promise<boolean> {
  return !!(await asyncDb.prepare('SELECT id FROM users WHERE id = ?').get<{ id: number }>(userId));
}

export async function upsertBillingCustomer(userId: number, stripeCustomerId: string): Promise<BillingCustomer> {
  await ensureBillingStorage();
  await asyncDb
    .prepare(
      `
      INSERT INTO billing_customers (user_id, stripe_customer_id, updated_at)
      VALUES (?, ?, CURRENT_TIMESTAMP)
      ON CONFLICT(user_id) DO UPDATE SET
        stripe_customer_id = excluded.stripe_customer_id,
        updated_at = CURRENT_TIMESTAMP
    `,
    )
    .run(userId, stripeCustomerId);

  const customer = await getBillingCustomerForUser(userId);
  if (!customer) throw new Error('Failed to persist billing customer.');
  return customer;
}

export async function getProcessedStripeWebhookEvent(eventId: string): Promise<BillingWebhookEvent | undefined> {
  await ensureBillingStorage();
  return asyncDb.prepare('SELECT * FROM billing_webhook_events WHERE id = ?').get<BillingWebhookEvent>(eventId);
}

export async function recordProcessedStripeWebhookEvent(input: {
  eventId: string;
  type: string;
  stripeCreated?: number | null;
}): Promise<void> {
  await ensureBillingStorage();
  await asyncDb
    .prepare(
      `
      INSERT OR IGNORE INTO billing_webhook_events (id, type, stripe_created, processed_at)
      VALUES (?, ?, ?, CURRENT_TIMESTAMP)
    `,
    )
    .run(input.eventId, input.type, input.stripeCreated ?? null);
}

export function freeBillingState(userId: number): FreeBillingState {
  return {
    user_id: userId,
    status: 'free',
    plan_key: 'free',
    stripe_customer_id: null,
    stripe_subscription_id: null,
    stripe_price_id: null,
    current_period_start: null,
    current_period_end: null,
    trial_start: null,
    trial_end: null,
    cancel_at_period_end: 0,
    canceled_at: null,
  };
}

export async function getBillingSubscriptionForUser(
  userId: number,
): Promise<BillingSubscriptionState | FreeBillingState> {
  await ensureBillingStorage();
  const row = await asyncDb
    .prepare(
      `
      SELECT
        s.id,
        s.user_id,
        s.billing_customer_id,
        s.stripe_customer_id,
        s.stripe_subscription_id,
        s.status,
        s.plan_key,
        s.stripe_price_id,
        s.current_period_start,
        s.current_period_end,
        s.trial_start,
        s.trial_end,
        s.cancel_at_period_end,
        s.canceled_at,
        s.created_at,
        s.updated_at,
        c.id AS customer_id,
        c.user_id AS customer_user_id,
        c.stripe_customer_id AS customer_stripe_customer_id,
        c.created_at AS customer_created_at,
        c.updated_at AS customer_updated_at
      FROM billing_subscriptions s
      JOIN billing_customers c ON c.id = s.billing_customer_id
      WHERE s.user_id = ?
      ORDER BY
        CASE
          WHEN s.status IN ('active', 'trialing') THEN 0
          WHEN s.status IN ('past_due', 'unpaid') THEN 1
          ELSE 2
        END,
        s.updated_at DESC,
        s.id DESC
      LIMIT 1
    `,
    )
    .get<
      BillingSubscription & {
        customer_id: number;
        customer_user_id: number;
        customer_stripe_customer_id: string;
        customer_created_at: string;
        customer_updated_at: string;
      }
    >(userId);

  if (!row) return freeBillingState(userId);

  const {
    customer_id,
    customer_user_id,
    customer_stripe_customer_id,
    customer_created_at,
    customer_updated_at,
    ...subscription
  } = row;

  return {
    ...subscription,
    customer: {
      id: customer_id,
      user_id: customer_user_id,
      stripe_customer_id: customer_stripe_customer_id,
      created_at: customer_created_at,
      updated_at: customer_updated_at,
    },
  };
}

export async function getBillingSubscriptionByStripeId(
  stripeSubscriptionId: string,
): Promise<BillingSubscription | undefined> {
  await ensureBillingStorage();
  return asyncDb
    .prepare('SELECT * FROM billing_subscriptions WHERE stripe_subscription_id = ?')
    .get<BillingSubscription>(stripeSubscriptionId);
}

export async function getBillingUserIdByStripeSubscriptionId(
  stripeSubscriptionId: string,
): Promise<number | undefined> {
  return (await getBillingSubscriptionByStripeId(stripeSubscriptionId))?.user_id;
}

export async function getBillingUserIdByStripeCustomerId(stripeCustomerId: string): Promise<number | undefined> {
  return (await getBillingCustomerByStripeId(stripeCustomerId))?.user_id;
}

export async function markStripeSubscriptionPaymentFailed(
  stripeSubscriptionId: string,
): Promise<BillingSubscription | undefined> {
  const existing = await getBillingSubscriptionByStripeId(stripeSubscriptionId);
  if (!existing) return undefined;

  const terminalOrAlreadyFailed = new Set(['canceled', 'unpaid', 'incomplete', 'incomplete_expired']);
  const nextStatus = terminalOrAlreadyFailed.has(existing.status) ? existing.status : 'past_due';
  await asyncDb
    .prepare(
      `
      UPDATE billing_subscriptions
      SET status = ?, updated_at = CURRENT_TIMESTAMP
      WHERE stripe_subscription_id = ?
    `,
    )
    .run(nextStatus, stripeSubscriptionId);
  return getBillingSubscriptionByStripeId(stripeSubscriptionId);
}

export async function markStripeCustomerSubscriptionsCanceled(
  stripeCustomerId: string,
  canceledAt?: string | Date | null,
): Promise<number> {
  const result = await asyncDb
    .prepare(
      `
      UPDATE billing_subscriptions
      SET
        status = 'canceled',
        canceled_at = COALESCE(canceled_at, ?),
        updated_at = CURRENT_TIMESTAMP
      WHERE stripe_customer_id = ?
        AND status <> 'canceled'
    `,
    )
    .run(isoOrNull(canceledAt ?? new Date()), stripeCustomerId);
  return result.changes;
}

export async function upsertStripeSubscriptionState(
  input: UpsertStripeSubscriptionInput,
): Promise<BillingSubscriptionState> {
  return asyncDb.transaction(async () => {
    const customer = await upsertBillingCustomer(input.userId, input.stripeCustomerId);

    await asyncDb
      .prepare(
        `
        INSERT INTO billing_subscriptions (
          user_id,
          billing_customer_id,
          stripe_customer_id,
          stripe_subscription_id,
          status,
          plan_key,
          stripe_price_id,
          current_period_start,
          current_period_end,
          trial_start,
          trial_end,
          cancel_at_period_end,
          canceled_at,
          updated_at
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
        ON CONFLICT(stripe_subscription_id) DO UPDATE SET
          user_id = excluded.user_id,
          billing_customer_id = excluded.billing_customer_id,
          stripe_customer_id = excluded.stripe_customer_id,
          status = excluded.status,
          plan_key = excluded.plan_key,
          stripe_price_id = excluded.stripe_price_id,
          current_period_start = excluded.current_period_start,
          current_period_end = excluded.current_period_end,
          trial_start = excluded.trial_start,
          trial_end = excluded.trial_end,
          cancel_at_period_end = excluded.cancel_at_period_end,
          canceled_at = excluded.canceled_at,
          updated_at = CURRENT_TIMESTAMP
      `,
      )
      .run(
        input.userId,
        customer.id,
        input.stripeCustomerId,
        input.stripeSubscriptionId,
        input.status,
        input.planKey,
        input.stripePriceId ?? null,
        isoOrNull(input.currentPeriodStart),
        isoOrNull(input.currentPeriodEnd),
        isoOrNull(input.trialStart),
        isoOrNull(input.trialEnd),
        input.cancelAtPeriodEnd ? 1 : 0,
        isoOrNull(input.canceledAt),
      );

    const state = await getBillingSubscriptionForUser(input.userId);
    if ('customer' in state) return state;
    throw new Error('Failed to persist billing subscription.');
  })();
}
